import { Inter } from "next/font/google";
import "./globals.css";
import Sidebar from "./ui/horoAlejandro/sidebar";
import DailyPhrase from "./ui/horoAlejandro/components/dailyPhrase";



const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <div className="mt-4">
          
          <div className="text-center p-2">
            <DailyPhrase/>
          </div>
          

          <div className="flex  m-4">
            <div className="w-3/4 m-1 flex	">
                {children}
            </div>
              <Sidebar/>
          </div>

        </div>
      </body>
    </html>
  );
}
